POST http://localhost:4000/contact
Content-Type: application/json

{
    "firstName": "Matheus",
    "surname": "Kruger",
    "email": "ms-kruger1@hotmail.com"
}

###

GET http://localhost:4000/contact
Content-Type: application/json

###

GET http://localhost:4000/contact/63924ea4640c5da792993225
Content-Type: application/json